notemakerproject/notemakerapp/urls.py
from django.urls import path
from notemakerapp import views

app_name='notemakerapp'

urlpatterns=[
    path('register/',views.register_view,name="register"),
    path('index/',views.index,name="index"),
    path('login/',views.user_login,name="login"),
    path('logout/',views.user_logout,name="logout"),
    path('notes/',views.notes_view,name="notes"),
    path('note_add/',views.note_add_view,name="note_add"),
    path('about/',views.about,name="about"),
]

notemakerproject/notemakerproject/urls.py
from django.contrib import admin
from django.urls import path,include
from notemakerapp import views
urlpatterns = [
    path('',views.index,name="index"),
    path('notemakerapp/',include('notemakerapp.urls')),
    path('admin/', admin.site.urls),
]

notemakerproject/notemakerapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Note(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    title=models.CharField(max_length=30)
    text=models.TextField()
    def __str__(self):
        return self.title

notemakerproject/notemakerapp/forms.py
from django import forms
from django.contrib.auth.models import User
from notemakerapp.models import Note

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model=User
        fields=('username','email','password')

class NoteForm(forms.ModelForm):
    class Meta:
        model=Note
        fields="__all__"

notemakerproject/notemakerapp/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from notemakerapp.models import Note
from notemakerapp.forms import UserForm,NoteForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
# Create your views here.
def index(request):
    return render(request,'notemakerapp/index.html')

def about(request):
    return render(request,'notemakerapp/about.html')

@login_required
def special(request):
    return HttpResponse('You are logged in!')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register_view(request):
    registered=False
    if request.method=="POST":
        user_form=UserForm(data=request.POST)

        if user_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            registered=True
        else:
            print(user_form.errors)

    else:
        user_form=UserForm()

    return render(request,'notemakerapp/register.html',{'user_form':user_form,
                                                        'registered':registered})

def user_login(request):
    if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
               print('Account not active')
        else:
            print('Username{}and password{}'.format(username,password))
    else:
        return render(request,'notemakerapp/login.html',{})

def note_add_view(request):
    if request.method=="POST":
        note_form=NoteForm(data=request.POST)
        if note_form.is_valid():
            note_form.save()
        else:
            print('Error in validation')
    else:
        note_form=NoteForm()
    return render(request,'notemakerapp/note_form.html',{'note_form':note_form})


def notes_view(request):
    logged_in_user = request.user
    logged_in_user_posts = Note.objects.filter(user=logged_in_user)
    return render(request, 'notemakerapp/notes.html', {'notes': logged_in_user_posts})

notemakerproject/templates/notemakerapp/about.html
{%extends 'notemakerapp/base.html'%}
{%block body_block%}
<div class="jumbotron">
  <p>Take your important notes using this easy Note maker app on both mobiles and tablets. It lets you manage your notes easily by adding it, updating it and deleting it. New version lets you add reminder as well and get notified on your selected time with notification.</p>
</div>
{%endblock%}

notemakerproject/templates/notemakerapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>NoteMaker</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand" href="#">NoteMaker</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'notemakerapp:index'%}">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'notemakerapp:register'%}">Register</a>
      </li>
    {%if user.is_authenticated%}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'notemakerapp:logout'%}">Logout</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'notemakerapp:notes'%}">YourNotes</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'notemakerapp:note_add' %}">AddNotes</a>
    </li>
    {%else%}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'notemakerapp:login'%}">Login</a>
    </li>
    {%endif%}
  </ul>
  </div>
</nav>
<div class="container">
  {%block body_block%}
  {%endblock%}
</div>
  </body>
</html>

notemakerproject/templates/notemakerapp/index.html
{%extends "notemakerapp/base.html"%}
{%block body_block%}
<div class="jumbotron">
  <h1 class="display-4">Notemaker</h1>
  <p class="lead">Forget what to do when to do save the work you have to do here!</p>
  <hr class="my-4">
  <p class="lead">
    <a class="btn btn-success btn-lg" href="{%url 'notemakerapp:about'%}" role="button">About</a>
  </p>
</div>
{%endblock%}

notemakerproject/templates/notemakerapp/login.html
{%extends 'notemakerapp/base.html'%}
{%block body_block%}
<div class="jumbotron">
  <form method="post">
    {%csrf_token%}
    <label for="username">Username:</label>
    <input type="text" name="username">
    <label for="password">Password:</label>
    <input type="password" name="password">
    <input type="submit"  value="Login">
  </form>
</div>
{%endblock%}

notemakerproject/templates/notemakerapp/note_form.html
{%extends 'notemakerapp/base.html'%}
{%block body_block%}
<div class="container">
  <div class="jumbotron">
    <form  method="post">
      {%csrf_token%}
      {{note_form.as_p}}
      <input type="submit" name="" value="Add">
    </form>
  </div>
</div>
{%endblock%}

notemakerproject/templates/notemakerapp/notes.html
{%extends 'notemakerapp/base.html'%}
{%block body_block%}
{%if user.is_authenticated%}
{%if notes%}
  {%for note in notes%}
      <div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{note.title}}</h5>
    <p class="card-text">{{note.text}}</p>
  </div>
  {%endfor%}
</div>
{%else%}
{%endif%}

    {%else%}
    <p>Go on create your first note</p>
    {%endif%}
    {%endblock%}

notemakerproject/templates/notemakerapp/register.html
{%extends 'notemakerapp/base.html'%}
{%block body_block%}
<div class="jumbotron">
  {%if registered%}
  <h1>Thanks for registering</h1>
  {%else%}
  <form method="post">
    {%csrf_token%}
    {{user_form.as_p}}
    <input type="submit" value="Register">
  </form>
  {%endif%}
</div>
{%endblock%}